name: Auto Request Review

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: necojackarc/auto-request-review@v0.10.0
        with:
          token: ${{ github.token}}
          # token: ${{ secrets.WCLUB_DEV_ACCESS_TOKEN }}
          config: .github/workflows/reviewers.yml
          use_local: true
